export const basicMeal = {
buttons: { 
    A: false, 
    B: false, 
    C: false, 
    D: false, 
    E: false, 
    F: false, 
    G: false,
    H: false, 
    I: false, 
    J: false, 
    K: false, 
    L: false, 
    M: false,
    N: false,
    O: false,
    P: false,
    Q: false,
    R: false,
    S: false,
    T: false,
    U: false,
    V: false,
    W: false },

    score: 0,

    date: new Date()
}

export const testMeals = [
    {
        buttons: { 
            A: true, 
            B: true, 
            C: false, 
            D: false, 
            E: false, 
            F: false, 
            G: false,
            H: false, 
            I: false, 
            J: false, 
            K: false, 
            L: false, 
            M: false,
            N: false,
            O: false,
            P: false,
            Q: false,
            R: false,
            S: false,
            T: false,
            U: false,
            V: false,
            W: false },
        
            score: 5,
        
            date: new Date('2019-07-13')
        },
        {
            buttons: { 
                A: true, 
                B: true, 
                C: false, 
                D: false, 
                E: false, 
                F: false, 
                G: false,
                H: false, 
                I: false, 
                J: false, 
                K: false, 
                L: false, 
                M: false,
                N: false,
                O: false,
                P: false,
                Q: false,
                R: false,
                S: false,
                T: false,
                U: false,
                V: false,
                W: false },
            
                score: 5,
            
                date: new Date('2019-07-14')
            },
            {
                buttons: { 
                    A: true, 
                    B: true, 
                    C: false, 
                    D: false, 
                    E: false, 
                    F: false, 
                    G: false,
                    H: false, 
                    I: false, 
                    J: false, 
                    K: false, 
                    L: false, 
                    M: false,
                    N: false,
                    O: false,
                    P: false,
                    Q: false,
                    R: false,
                    S: false,
                    T: false,
                    U: false,
                    V: false,
                    W: false },
                
                    score: 5,
                
                    date: new Date('2019-07-15')
                },
    {
    buttons: { 
        A: true, 
        B: true, 
        C: false, 
        D: false, 
        E: false, 
        F: false, 
        G: false,
        H: false, 
        I: false, 
        J: false, 
        K: false, 
        L: false, 
        M: false,
        N: false,
        O: false,
        P: false,
        Q: false,
        R: false,
        S: false,
        T: false,
        U: false,
        V: false,
        W: false },
    
        score: 5,
    
        date: new Date('2019-07-16')
    },
    {
        buttons: { 
            A: true, 
            B: true, 
            C: false, 
            D: false, 
            E: true, 
            F: true, 
            G: false,
            H: false, 
            I: false, 
            J: false, 
            K: false, 
            L: false, 
            M: false,
            N: false,
            O: false,
            P: false,
            Q: false,
            R: false,
            S: false,
            T: false,
            U: false,
            V: false,
            W: false },
        
            score: 15,
        
            date: new Date('2019-07-17')
        },
        {
            date: new Date('2019-07-18'),
            score: 3,
            buttons: { 
                A: true, 
                B: true, 
                C: false, 
                D: false, 
                E: false, 
                F: false, 
                G: false,
                H: false, 
                I: false, 
                J: false, 
                K: false, 
                L: false, 
                M: false,
                N: false,
                O: false,
                P: false,
                Q: false,
                R: false,
                S: false,
                T: false,
                U: false,
                V: false,
                W: false },
                
            
            }
    

];